volumes:
  node_modules:

services:
  database:
    build: ./database/
    ports: 
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=amplimind
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=coding-challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    
  server:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      database:
        condition: service_healthy
  
  web:
    build: ./frontend/
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/coding-challenge:/frontend
      - node_modules:/frontend/node_modules
    depends_on:
      - server
