services:
  server:
    build: ./backend/
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/backend
  web:
    build: ./frontend/
    ports:
      - "4200:4200"
    # volumes:
    #   - ./frontend/coding-challenge:/frontend
