from .application import TestApplicationApiView
from .challenge import GetChallengeAdminApiView, GetChallengeApplicationApiView, GetChallengesAdminApiView
from .testauth import AdminApiView, ApplicantApiView