# Generated by Django 4.1.7 on 2023-04-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeHeading', models.TextField()),
                ('challengeText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationId', models.CharField(max_length=8)),
                ('challengeId', models.IntegerField()),
                ('operatingSystem', models.CharField(blank=True, max_length=100)),
                ('programmingLanguage', models.CharField(blank=True, max_length=100)),
                ('expiry', unixtimestampfield.fields.UnixTimeStampField()),
                ('submission', unixtimestampfield.fields.UnixTimeStampField(blank=True)),
                ('githubRepo', models.URLField(blank=True)),
                ('status', models.IntegerField(choices=[('0', 'Initial'), ('1', 'Challenge Started'), ('2', 'In Review'), ('3', 'Completed'), ('4', 'Archived'), ("<class 'api.models.status.Status.Meta'>", 'Meta')], default='0')),
                ('applicantEmail', models.CharField(max_length=50)),
                ('created', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modified', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
