# Generated by Django 4.1.7 on 2023-04-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='programingLanguage',
            new_name='programmingLanguage',
        ),
    ]
