# Generated by Django 4.1.7 on 2023-03-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
