# Generated by Django 4.1.7 on 2023-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programinglanguage_application_programminglanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='applicationId',
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
