# Generated by Django 4.1.7 on 2023-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_test_completed_remove_test_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='extra',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
