# Generated by Django 4.1.7 on 2023-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='extra3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
