# Generated by Django 4.1.7 on 2023-04-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='user_id',
        ),
    ]
