# Generated by Django 4.1.7 on 2023-04-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_test_extra3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='extra3',
        ),
    ]
