# Generated by Django 4.1.7 on 2023-04-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_application_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='userId',
        ),
    ]
