# Generated by Django 4.1.7 on 2023-04-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_application_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='userId',
            new_name='user',
        ),
    ]
