# Generated by Django 4.1.7 on 2023-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_application_githubrepo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
