name: Django CI

on:
  push:
    branches: [ "feature/add-linter-to-codingchallenge-project" ]
  pull_request:
    branches: [ "feature/add-linter-to-codingchallenge-project" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/codingchallenge/manage.py test
